# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20171025_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_user_friend_+', to='login_app.User'),
        ),
    ]
